version: '3'

networks:
    skyshard:
       driver: bridge

services:
    proxy:
        image: neo4j/neo4j-experimental:4.0.0-beta03mr03-enterprise
        hostname: proxy
        container_name: proxy
        ports:
        - "7474:7474"
        - "7687:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            NEO4J_fabric_database_name: fabric

            NEO4J_fabric_graph_0_name: january2020
            NEO4J_fabric_graph_0_uri: neo4j://january:7687
            # NEO4J_fabric_graph_0_database: january
            
            NEO4J_fabric_graph_1_name: february2020
            NEO4J_fabric_graph_1_uri: neo4j://february:7687
            # NEO4J_fabric_graph_1_database: february
            
            NEO4J_fabric_graph_2_name: march2020
            NEO4J_fabric_graph_2_uri: neo4j://march:7687
            # NEO4J_fabric_graph_2_database: march

            NEO4J_fabric_graph_3_name: airports
            NEO4J_fabric_graph_3_uri: neo4j://airports:7687
            # NEO4J_fabric_graph_2_database: airports
            
        networks:
        - skyshard

    january:
        image: neo4j/neo4j-experimental:4.0.0-beta03mr03-enterprise
        hostname: "january"
        container_name: january
        ports:
        - "17474:7474"
        - "17687:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            # NEO4J_dbms_default__database: "january"

            NEO4J_dbms_connector_bolt_advertised__address: "january:7687"
        
        volumes:
        - "./cypher:/cypher"

        networks:
        - skyshard

    february:
        image: neo4j/neo4j-experimental:4.0.0-beta03mr03-enterprise
        hostname: "february"
        container_name: february
        ports:
        - "27474:7474"
        - "27687:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            # NEO4J_dbms_default__database: "february"

            NEO4J_dbms_connector_bolt_advertised__address: "february:7687"
            
        volumes:
        - "./cypher:/cypher"
            
        networks:
        - skyshard
    
    march:
        image: neo4j/neo4j-experimental:4.0.0-beta03mr03-enterprise
        hostname: "march"
        container_name: march
        ports:
        - "37474:7474"
        - "37687:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            # NEO4J_dbms_default__database: "march"
            
            NEO4J_dbms_connector_bolt_advertised__address: "march:7687"

        volumes:
            - "./cypher:/cypher"
            
        networks:
        - skyshard

    airports:
        image: neo4j/neo4j-experimental:4.0.0-beta03mr03-enterprise
        hostname: "airports"
        container_name: airports
        ports:
        - "47474:7474"
        - "47687:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            # NEO4J_dbms_default__database: "airports"

            NEO4J_dbms_connector_bolt_advertised__address: "airports:7687"

        networks:
        - skyshard
